### ISSUE TITLE
No Release. No Video demo

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Purplelimited#132]
Last day of Summer was July 28. There is no release, no video demo, no commits.

**Comment by ABuonantuono** [comment]
https://drive.google.com/file/d/1TaOp8Ka8GvILRLziLG2Fy_y9r-7Yehrq/view?usp=drivesdk

https://user-images.githubusercontent.com/89362652/182038699-b63d15b3-8a8a-457e-a186-f774e3a40893.mp4
